# Autor: Daniel Benjamin Perez Morales
# GitHub: https://github.com/DanielPerezMoralesDev13
# Correo electrónico: danielperezdev@proton.me

# Makefile simple para compilar un programa en C

# Nombre del ejecutable
programa: src/main.c
	gcc -o programa src/main.c

# Regla para limpiar los archivos generados
clean:
	rm -f programa
